name: Como usar variaveis de ambiente
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "Valor WORKFLOW"
jobs:
  teste-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor JOB teste-env"
    steps:
      - name: Execucao
        env:
          ENV_ACTIONS: "Valor ACTION - Execucao"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
      - name: Execucao 2
        env:
          ENV_ACTIONS: "Valor ACTION - Segunda Execucao"
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
          echo "$ENV_ACTION"
  teste-env-2:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "Valor JOB SEGUNDO teste-env"
    steps:
      - name: Execucao
        run: |
          echo "$ENV_WORKFLOW"
          echo "$ENV_JOB"
      
      
          
